traefik=~/infrastructure/compose/traefik
portainer=~/infrastructure/compose/portainer
postgres=~/infrastructure/compose/postgres
redis=~/infrastructure/compose/redis
minio=~/infrastructure/compose/minio
mailpit=~/infrastructure/compose/mailpit
